# Generated by Django 5.1.4 on 2025-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icons', models.FileField(upload_to='icons/')),
                ('history', models.TextField()),
                ('photos', models.FileField(upload_to='photos/')),
            ],
        ),
    ]
