# Generated by Django 5.1.4 on 2025-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=160)),
                ('history', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('photo1', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
